# Usar una imagen oficial de Node.js como base
FROM node:20-alpine

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json primero
COPY package*.json ./

# Instalar dependencias de producción
RUN npm install --production

# Copiar el resto de tu aplicación
COPY . .

# Exponer el puerto que usa tu app
EXPOSE 3000

# Comando para ejecutar la app
CMD ["node", "index.js"]
